_BASE_: "../base-prompt-adv.yaml"
OUTPUT_DIR: #TODO: need to specify output path here
DATA:
  NAME: "vtab-cifar(num_classes=10)"
  DATAPATH: #TODO: need to specify here
  NUMBER_CLASSES: 10
  MULTILABEL: False
  BATCH_SIZE: 64
  FEATURE: "ARES_Swin_base_patch4_window7_224_AT"
  TRAIN_NUM_PERCENT: 100
MODEL:
  TYPE: "swin"
  PROMPT:
    NUM_TOKENS: 10
    DEEP: True
    DROPOUT: 0.1
  MODEL_ROOT: "pretrain"
  RESIZE: True
  SAVE_CHECKPOINT: True
SOLVER:
  BASE_LR: 0.5
  WEIGHT_DECAY: 0.001
  TOTAL_EPOCH: 20
ADV:
  TRAIN_ATTACK_EPS: 0.03137254901
  TRAIN_ATTACK_STEPS: 7
  VAL_ATTACK_EPS: 0.03137254901
  VAL_ATTACK_STEPS: 10
  HALF_ADV: False
VAL_FREQ: 1