NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: "results"
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "end2end"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  WARMUP_EPOCH: 10
  LOSS: "softmax"
  OPTIMIZER: "adamw"
  MOMENTUM: 0.9
  LOG_EVERY_N: 100
  TOTAL_EPOCH: 100
  PATIENCE: 300

DATA:
  NUM_WORKERS: 8
  TRAIN_NUM_PERCENT: 100
  FEATURE: "adv_sup_vit16_imagenet"
TRAIN_MODE: "adv"

